export const templatesGallery = [
  {
    title: "Template / SaaS Starter",
    slug: "template-saas-starter",
    src: "/templates/saas-starter.png",
    alt:
      "SaaS landing with hero, logos, feature grid, pricing, FAQ, and footer",
    category: "template",
    href: "/templates/saas-starter",
    sections: [
      "Hero/With Logos",
      "Features/3-Column",
      "Integrations",
      "Pricing/Tiered",
      "FAQ/Accordion",
      "CTA/Banner",
      "Footer/Columns",
    ],
    tags: ["saas", "startup", "light"],
  },
  {
    title: "Template / Creator Portfolio",
    slug: "template-creator-portfolio",
    src: "/templates/portfolio.png",
    alt: "Portfolio with intro hero, gallery, about, services, and contact",
    category: "template",
    href: "/templates/creator-portfolio",
    sections: [
      "Hero/Centered",
      "Gallery/Grid",
      "About/Split",
      "Services/Cards",
      "Testimonials",
      "Contact/Form",
      "Footer/Minimal",
    ],
    tags: ["creator", "artist", "portfolio"],
  },
  {
    title: "Template / Agency Studio",
    slug: "template-agency-studio",
    src: "/templates/agency.png",
    alt: "Agency site with case studies, services, process, and contact CTA",
    category: "template",
    href: "/templates/agency-studio",
    sections: [
      "Hero/Split",
      "Services/Icons",
      "Work/Case Studies",
      "Process/Steps",
      "Testimonials",
      "CTA/Strip",
      "Footer/Columns",
    ],
    tags: ["agency", "studio", "business"],
  },
  {
    title: "Template / Sales Funnel",
    slug: "template-link-in-bio",
    src: "/templates/sales-funnel.png",
    alt:
      "Link hub with avatar, bio, social links, featured content, and newsletter",
    category: "template",
    href: "/templates/link-in-bio",
    sections: [
      "Hero/Profile",
      "Links/List",
      "Featured/Carousel",
      "Newsletter/Inline",
      "Footer/Minimal",
    ],
    tags: ["creator", "social", "mobile-first"],
  },
  {
    title: "Template / E-commerce Landing",
    slug: "template-ecommerce-landing",
    src: "/templates/ecommerce.png",
    alt:
      "Product-focused landing with hero, benefits, gallery, reviews, and purchase CTA",
    category: "template",
    href: "/templates/ecommerce-landing",
    sections: [
      "Hero/Product",
      "Benefits/3-Up",
      "Gallery/Carousel",
      "Reviews",
      "FAQ",
      "CTA/Purchase",
      "Footer/Columns",
    ],
    tags: ["ecommerce", "product", "conversion"],
  },
  {
    title: "Template / Course & Coaching",
    slug: "template-course-coaching",
    src: "/templates/courses.webp",
    alt:
      "Course landing with outcomes, curriculum, instructor bio, pricing, and FAQ",
    category: "template",
    href: "/templates/course-coaching",
    sections: [
      "Hero/With Logos",
      "Outcomes/Icons",
      "Curriculum/Chapters",
      "Instructor/Bio",
      "Pricing/Cards",
      "FAQ",
      "Footer/Newsletter",
    ],
    tags: ["education", "creator", "info-product"],
  },
  {
    title: "Template / Mobile App",
    slug: "template-mobile-app",
    src: "/templates/software.jpeg",
    alt: "App promo with feature highlights, screenshots, and store badges",
    category: "template",
    href: "/templates/mobile-app",
    sections: [
      "Hero/App Badges",
      "Features/Screenshots",
      "How It Works/Steps",
      "Testimonials",
      "CTA/Download",
      "Footer/Minimal",
    ],
    tags: ["app", "product", "light"],
  },
  {
    title: "Template / Event & Workshop",
    slug: "template-event-workshop",
    src: "/templates/event.png",
    alt: "Event page with agenda, speakers, schedule, location, and ticket CTA",
    category: "template",
    href: "/templates/event-workshop",
    sections: [
      "Hero/Event",
      "Speakers/Grid",
      "Agenda/Timeline",
      "Location/Map",
      "FAQ",
      "CTA/Tickets",
      "Footer/Minimal",
    ],
    tags: ["event", "workshop", "ticketing"],
  },
  {
    title: "Template / Nonprofit & Cause",
    slug: "template-nonprofit-cause",
    src: "/templates/nonprofit.jpg",
    alt:
      "Cause page with mission, impact stats, stories, donate CTA, and newsletter",
    category: "template",
    href: "/templates/nonprofit-cause",
    sections: [
      "Hero/Statement",
      "Impact/Stats",
      "Stories/Cards",
      "Partners/Logos",
      "CTA/Donate",
      "Newsletter",
      "Footer/Columns",
    ],
    tags: ["nonprofit", "cause", "donations"],
  },
  {
    title: "Template / Restaurant & Cafe",
    slug: "template-restaurant-cafe",
    src: "/templates/cafe.avif",
    alt:
      "Food venue page with hero, menu highlights, gallery, hours, location, and booking",
    category: "template",
    href: "/templates/restaurant-cafe",
    sections: [
      "Hero/Photo",
      "Menu/Highlights",
      "Gallery/Grid",
      "Reviews",
      "Hours & Location",
      "CTA/Book",
      "Footer/Minimal",
    ],
    tags: ["local", "food", "booking"],
  },
];
